name: nurow_devp
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lite_rolling_switch: ^1.0.1
  flutter_barcode_scanner: ^2.0.0
  mqtt_client: ^9.6.5
  flutter_launcher_icons: ^0.9.2
  flutter_bloc: ^8.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

  flutter_lints: ^1.0.0

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "images/1024.png"

flutter:

  uses-material-design: true

  assets:
    - images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  